### ISSUE TITLE
systemctl not working in container - 'Failed to connect to bus: No such file or directory'

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/docker-fedora27-ansible#2]
With the current image and default init command, I get the following:

```
# systemctl status
Failed to connect to bus: No such file or directory
```

And when running an Ansible playbook which manages a service:

```
TASK [geerlingguy.docker : Ensure Docker is started and enabled at boot.] ******
fatal: [instance]: FAILED! => {"changed": false, "cmd": "/usr/bin/systemctl", "msg": "Failed to connect to bus: No such file or directory", "rc": 1, "stderr": "Failed to connect to bus: No such file or directory\n", "stderr_lines": ["Failed to connect to bus: No such file or directory"], "stdout": "", "stdout_lines": []}
```

Looking into the issue, it seems `dbus-daemon` may not be running.

But if I do the following:

```
mkdir -p /run/dbus
dbus-daemon --system
```

It seems to start, but then I get:

```
# systemctl status
Failed to read server status: Launch helper exited with unknown return code 1
```

**Comment by geerlingguy** [comment]
So this image—which seems _almost_ identical to my current build—currently works out of the box: https://hub.docker.com/r/unop/fedora-systemd/

**Comment by geerlingguy** [comment]
Looks like it might just be the `init` command...

```
-CMD ["/usr/lib/systemd/systemd"]
+CMD ["/usr/sbin/init"]
```

**Comment by geerlingguy** [comment]
Simply `run`ning the container seems to work now. But in my molecule environment it is not. Might be a volume binding issue.

**Comment by JimmyTournemaine** [comment]
Same issues using `geerlingguy/docker-centos8-ansible` docker image using molecule.
Using `CMD: ["/usr/sbin/init"]` fix it too.

```
- name: instance
    image: "geerlingguy/docker-centos8-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/sbin/init"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
```
